<?php

/**
 * Implements hook_theme().
 */
function shortcode_builder_theme($existing, $type, $theme, $path) {
  return array(
    // Base
    'shortcode_builder_base' => array(
      'variables' => array('attributes' => array(), 'text' => NULL,),
    ),
    // Container
    'shortcode_builder_container' => array(
      'variables' => array('attributes' => array(), 'text' => NULL, 'container' => NULL,),
    ),
    // Row
    'shortcode_builder_row' => array(
      'variables' => array('src' => NULL, 'alt' => NULL, 'class' => ''),
    ),
    // Column
    'shortcode_builder_column' => array(
      'variables' => array('url' => NULL, 'attributes' => array(), 'text' => ''),
    ),
    // Custom Text
    'shortcode_text_widget' => array(
      'variables' => array('url' => NULL, 'attributes' => array(), 'text' => ''),
    ),
    // Entity Field
    'shortcode_field_widget' => array(
      'variables' => array('class' => NULL, 'text' => ''),
    ),
    // Image
    'shortcode_image_widget' => array(
      'variables' => array('type' => 'div', 'attributes' => array(), 'text' => ''),
    ),
    // Block
    'shortcode_block_widget' => array(
      'variables' => array('type' => 'div', 'attributes' => array(), 'text' => ''),
    ),
  );
}
